name: NDK build

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
      - 'dev/**'
      - 'feat/**'
    paths-ignore:
      - ".gitignore"
      - "**.yml"
      - "!.github/workflows/ndk-build.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: true
          lfs: true

      - uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Create ndkpath.txt
        run: |
          echo "$ANDROID_NDK_LATEST_HOME" > ${GITHUB_WORKSPACE}/ndkpath.txt
          cat ${GITHUB_WORKSPACE}/ndkpath.txt

      - name: Extract version
        if: startsWith(github.ref, 'refs/tags/v')
        id: version
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> ${GITHUB_OUTPUT}
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> ${GITHUB_OUTPUT}

      # update the qpm define to be correct
      - name: Add Version define to qpm
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/github-script@v6
        with:
          script:
            const fs = require('fs');
            await fs.readFile("qpm.json", function read(err, data) {
              const qpm = JSON.parse(data);
              qpm.info.additionalData.compileOptions = {
                cppFlags:[ "-DKALEB_VERSION=\"${{ steps.version.outputs.VERSION }}\""]
              };

              await fs.writeFile("qpm.json", JSON.stringify(qpm, null, 4), function (err) {
                if (err) {
                  return console.error(err);
                }
                console.log("file saved!");
              });
            });

      - name: Setup qpm
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: Fernthedev/qpm-action@main
        with:
          workflow_token: ${{ secrets.GITHUB_TOKEN }}
          restore: true
          cache: false
          publish: false

      - name: Setup qpm for release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: Fernthedev/qpm-action@main
        with:
          workflow_token: ${{ secrets.GITHUB_TOKEN }}
          restore: true
          cache: false
          publish: true
          publish_token: ${{ secrets.QPM_KEY }}
          version: ${{ steps.version.outputs.VERSION }}
          tag: ${{ steps.version.outputs.TAG }}
          qpm_release_bin: false
          qpm_debug_bin: false

      - name: build
        run: pwsh ./scripts/build.ps1

      - name: Upload created header
        uses: actions/upload-artifact@v2
        with:
          name: assets.hpp
          path: ./include/assets.hpp
          if-no-files-found: error

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          generate_release_notes: true
